version: '3.9'

services:
  tensorflow-dev:
    image: tensorflow-dev
    build:
      context: config
      dockerfile: Dockerfile
      args:
        USER: liushuai
    ports:
      - "6006:6006"
    volumes:
      - .:/workspace
