version: '3.9'

services:
  tensorflow-dev:
    image: tensorflow-dev
    build:
      context: config
      dockerfile: Dockerfile
      args:
        USER: liushuai
        Local: local
    ports:
      - "6006:6006"
      - "22:25"
    volumes:
      - .:/workspace
      - $Local:${Local}
