version: "3.9"

services:
  tensorflow-dev:
    image: tensorflow-dev
    build:
      context: config
      dockerfile: Dockerfile
      args:
        USER: liushuai
        Local: local
    ports:
      - "6006:6006"
      - "22:25"
    volumes:
      - ${workspace}:/workspace
      - $Local:${Local}
    command: bash -c '
      REPOSITORY=${workspace} &&
      pushd ${workspace} &&
      mkdir -p auto_tools &&
      popd &&
      bash -c "while sleep 1000; do :; done"
