version: '3.9'

services:
  pytorch-dev-latest:
    image: pytorch-dev-cudnn8-latest
    runtime: nvidia
    env_file: .devcontainer/devcontainer.env
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      shm_size: '8gb'
      args:
        USER: liushuai
    environment: 
      Pytorch_ENV: devlopmental
    container_name: pytorch-devlop-cudnn8-latest
    user: liushuai
    restart: 'always'
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - "6007:6007"
      - "23:23"
    volumes:
      - /home/liushuai/.config/nvim:/home/liushuai/.config/nvim
      - /home/liushuai/.local/nvim:/home/liushuai/.local/nvim
      - /home/liushuai/.ssh:/home/liushuai/.ssh
      - /home/liushuai/.vscode/:/home/liushuai/.vscode
      - /home/liushuai/pytorch:/home/liushuai/pytorch
      - /home/liushuai/pytorch/build:/home/liushuai/pytorch/build
