version: '3.9'

services:
  pytorch-dev:
    image: pytorch-dev
    env_file: .devcontainer/devcontainer.env
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      shm_size: '8gb'
      args:
        USER: root
        Local: local
    environment: 
      Tensorflow_ENV: devlopmental
    container_name: pytorch-devlop
    user: liushuai
    restart: 'always'
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - "6006:6006"
      - "22:25"
    volumes:
      - ${PWD}:/workspace
      - /home/liushuai/.zshrc:/home/liushuai/.zshrc
      - /home/liushuai/.oh-my-zsh:/home/liushuai/.oh-my-zsh
      - /home/liushuai/.vimrc:/home/liushuai/.vimrc
      - /home/liushuai/.vscode/:/home/liushuai/.vscode
      - /home/liushuai/test:/home/liushuai/pytorch/test
      - /home/liushuai/pytorch/build:/root/pytorch/build
