version: '3.9'

services:
  pytorch-dev-latest:
    image: pytorch-dev-latest
    runtime: nvidia
    env_file: .devcontainer/devcontainer.env
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      shm_size: '8gb'
      args:
        USER: root
    environment: 
      Tensorflow_ENV: devlopmental
    container_name: pytorch-devlop-latest
    user: liushuai
    restart: 'always'
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - "6007:6007"
      - "23:23"
    volumes:
      - /home/liushuai/.zshrc:/root/.zshrc
      - /home/liushuai/.oh-my-zsh:/root/.oh-my-zsh
      - /home/liushuai/.vimrc:/root/.vimrc
      - /home/liushuai/.vim:/root/.vim
      - /home/liushuai/.vscode/:/root/.vscode
      - /home/liushuai/pytorch:/root/pytorch
      - /home/liushuai/test:/root/pytorch/test
      - /home/liushuai/pytorch/build:/root/pytorch/build
