version: "3.9"
services:
  pytorch-cudnn-dev-latest:
    image: pytorch-dev-cudnn8-custom-latest
    runtime: nvidia
    env_file: .devcontainer/devcontainer.env
    build:
      context: .devcontainer
      dockerfile: Dockerfile.pytorch
      shm_size: "16gb"
      args:
        USER: ${USER}
    shm_size: 16gb
    environment:
      Pytorch_ENV: development
      USER: ${USER}
    container_name: pytorch-devlop-custom-ubuntu20-cudnn8-latest
    user: ${USER}
    restart: "always"
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - "6007:6007"
      - "23:23"
    volumes:
      - /home/liushuai/.config/nvim:/home/liushuai/.config/nvim
      - /home/liushuai/.ssh:/home/liushuai/.ssh
      - /home/liushuai/.tmux.conf:/home/liushuai/.tmux.conf
      - /home/liushuai/.vscode/:/home/liushuai/.vscode
      - /home/liushuai/pytorch:/home/liushuai/pytorch
      - /home/liushuai/pytorch/build:/home/liushuai/pytorch/build
      - /home/liushuai/openlab:/home/liushuai/openlab
      - /home/liushuai/下载:/home/liushuai/download
      - /home/liushuai/audio:/home/liushuai/audio
      - /home/liushuai/mmyolo:/home/liushuai/mmyolo
      - /home/liushuai/mmclassification:/home/liushuai/mmclassification
      - /home/liushuai/mmdetection:/home/liushuai/mmdetection
      - /home/liushuai/mmocr:/home/liushuai/mmocr
    command: /bin/sh -c "while sleep 1000; do :; done"
