version: "3.9"
services:
  pytorch-cudnn-dev-latest:
    image: pytorch-devlop-ubuntu20-cudnn8-debug
    runtime: nvidia
    env_file: .devcontainer/devcontainer.env
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      shm_size: "16gb"
      args:
        USER: ${USER}
    shm_size: 16gb
    environment:
      Pytorch_ENV: development
      USER: ${USER}
    container_name: pytorch-devlop-custom-ubuntu20-cudnn8-latest
    user: ${USER}
    restart: "always"
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - "6007:6007"
      - "23:23"
    volumes:
      - /home/liushuai/.local/nvim:/home/liushuai/.local/nvim
      - /home/liushuai/.ssh/id_rsa:/home/liushuai/.ssh/id_rsa
      - /home/liushuai/.ssh/id_rsa.pub:/home/liushuai/.ssh/id_rsa.pub
      - /home/liushuai/.tmux.conf:/home/liushuai/.tmux.conf
      - /home/liushuai/.vscode/:/home/liushuai/.vscode
      - /home/liushuai/pytorch:/home/liushuai/pytorch
      - /home/liushuai/pytorch/build:/home/liushuai/pytorch/build
      - /home/liushuai/openlab:/home/liushuai/openlab
    command: /bin/sh -c "while sleep 1000; do :; done"
