version: '3.9'

services:
  tensorflow-dev:
    image: tensorflow-dev-latest
    runtime: nvidia
    env_file: .devcontainer/devcontainer.env
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      shm_size: '8gb'
      args:
        USER: root
    environment: 
      Tensorflow_ENV: devlopmental
    container_name: tensorflow-devlop-lastest
    user: liushuai
    restart: 'always'
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - "6006:6006"
      - "25:25"
    volumes:
      - /home/liushuai/.zshrc:/root/.zshrc
      - /home/liushuai/.oh-my-zsh:/root/.oh-my-zsh
      - /home/liushuai/.vimrc:/root/.vimrc
      - /home/liushuai/.vscode/:/root/.vscode/
      - /home/liushuai/test:/root/tensorflow/test
      - /home/liushuai/.cache:/root/.cache
      - /home/liushuai/tensorflow:/root/tensorflow
