version: "3.9"
services:
  pytorch-cudnn-tensorrt8-latest:
    image: pytorch-dev-tensorrt-latest
    runtime: nvidia
    env_file: .devcontainer/devcontainer.env
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      shm_size: "16gb"
      args:
        USER: ${USER}
    shm_size: 16gb
    environment:
      Pytorch_ENV: development
      USER: ${USER}
    container_name: pytorch-devlop-ubuntu20-cudnn8-tensorrt-latest
    user: ${USER}
    restart: "always"
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - "6008:6008"
      - "24:24"
    volumes:
      - /home/liushuai/.config/nvim:/home/liushuai/.config/nvim
      - /home/liushuai/.ssh/id_rsa.pub:/home/liushuai/.ssh/id_rsa.pub
      - /home/liushuai/.tmux.conf:/home/liushuai/.tmux.conf
      - /home/liushuai/.vscode/:/home/liushuai/.vscode
      - /home/liushuai/下载:/home/liushuai/download
    command: /bin/sh -c "while sleep 1000; do :; done"
