FROM open-mmlab-dev as opem-mmlab-dev
ENV LANG C.UTF-8
ARG USER=root
ARG PASSWORD=574794581
ARG DEBIAN_FRONTEND=noninteractive

LABEL maintainer="bleedingfight <bleedingfight@126.com>"

USER ${USER}:${USER}
EXPOSE 25
USER ${USER}
WORKDIR ${HOME}
